frequency: 50  # Hz
two_d_mode: true  # If using 2D localization

# Input sources
odom0: /odometry
odom0_config: [true, true, true,  # x, y, z (pose)
               true, true, true,  # roll, pitch, yaw (orientation)
               true, true, true,  # x, y, z (velocity)
               false, false, false]  # Roll, pitch, yaw (angular velocity)

imu0: /imu_plugin/out
imu0_config: [false, false, false,
              true, true, true,   # Orientation
              true, true, true,   # Angular velocity
              true, true, true]   # Linear acceleration

pose0: /amcl_pose
pose0_config: [true, true, false,   # x, y, (no z)
               false, false, true,   # yaw (ignore roll, pitch)
               false, false, false,  # velocity
               false, false, false]  # angular velocity

# Output sources
publish_tf: true
publish_acceleration: false
publish_diagnostics: true


